### ISSUE TITLE
Code won't compile on Mac OS X 10.8

### ISSUE THREAD

**Issue by tellowkrinkle** [nikitakit/ucpp#14]
I have tcl, wine, and wput installed through macports.
When I run make, I get this error:
cd PPC603gnu && exec "make" -f Makefile_linux
Makefile_linux:10: *** Recursive variable `WIND_HOME' references itself (eventually).  Stop.
make: *** [all] Error 2
Is this supposed to work on macs?

**Comment by nikitakit** [comment]
Closing this since no new issues/comments have come up in a long time
