### ISSUE TITLE
UCPP doesn't download Windriver/GNU directory

### ISSUE THREAD

**Issue by Megapead** [nikitakit/ucpp#18]
wine: cannot find '/home/gabriel/.ucpp/gccdist/WindRiver/gnu/3.4.4-vxworks-6.3/x86-win32/bin/ccppc.exe'
 The directory does not exist within this path: "~/.ucpp/gccdist/WindRiver"

**Comment by nikitakit** [comment]
Closing, since this appears to have been resolved. Let me know if there are still issues
